language: python
sudo: required
services: docker

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

install:
  - sudo apt-get update -q
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 99
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 99
  - pip install matplotlib numpy tabulate pyyaml tensorflow

env:
    matrix:
      - CMD='test/setup.py --schemes quic --install-deps &&
        test/setup.py --schemes quic --setup &&
        test/test.py local --schemes quic -t 10'
      - CMD='SCHEMES="default_tcp vegas bbr ledbat pcc verus sprout webrtc
        scream copa taova calibrated_koho indigo" &&
        test/setup.py --schemes "$SCHEMES" --install-deps &&
        test/setup.py --schemes "$SCHEMES" --setup &&
        analysis/tests/test_analyze.py --schemes "$SCHEMES"'

script:
  - ./install_deps.sh && eval $CMD

notifications:
    email: false
