language: python
sudo: required
services: docker

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - g++-4.9
    - mahimahi

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 99

env:
    matrix:
        - CC_SCHEME='quic'
        - CC_SCHEME='webrtc'
        - CC_SCHEME='default_tcp'
        - CC_SCHEME='vegas'
        - CC_SCHEME='koho_cc'
        - CC_SCHEME='ledbat'
        - CC_SCHEME='pcc'
        - CC_SCHEME='verus'
        - CC_SCHEME='scream'
        - CC_SCHEME='sprout'
        - CC_SCHEME='taova'

script:
  - test/pre_setup.py
  - test/setup.py $CC_SCHEME
  - test/test.py -f 2 -t 10 $CC_SCHEME

notifications:
  slack: keithw:WjjCMz8yip3iQrHKBmkFGI1u
  email: false
